

INSERT INTO EMPRESAS (ID, NOME) VALUES (1, 'POSTO ABC');

INSERT INTO PRODUTOS (ID, DESCRICAO, PRECO_VENDA) VALUES (1, 'ÓLEO DIESEL', 5.5);
INSERT INTO PRODUTOS (ID, DESCRICAO, PRECO_VENDA) VALUES (2, 'GASOLINA', 5.25);

INSERT INTO IMPOSTOS (ID, DESCRICAO, ALIQUOTA) VALUES (1, 'ICMS', 13);

INSERT INTO PRODUTOS_IMPOSTOS (IMPOSTO_ID, PRODUTO_ID) VALUES (1, 1);
INSERT INTO PRODUTOS_IMPOSTOS (IMPOSTO_ID, PRODUTO_ID) VALUES (1, 2);

INSERT INTO TANQUES (ID, PRODUTO_ID, DESCRICAO) VALUES (1, 1, 'TANQUE 01');
INSERT INTO TANQUES (ID, PRODUTO_ID, DESCRICAO) VALUES (2, 2, 'TANQUE 02');

INSERT INTO BOMBAS (ID, TANQUE_ID, DESCRICAO) VALUES (1, 1, 'BOMBA 01');
INSERT INTO BOMBAS (ID, TANQUE_ID, DESCRICAO) VALUES (2, 2, 'BOMBA 02');
INSERT INTO BOMBAS (ID, TANQUE_ID, DESCRICAO) VALUES (3, 1, 'BOMBA 03');
INSERT INTO BOMBAS (ID, TANQUE_ID, DESCRICAO) VALUES (4, 2, 'BOMBA 04');